wallarm:
  enabled: true
  token: "" # Put your node token here

image:
  repository: wallarm/kong-oss-preview
  tag: "2.7-ubuntu-4.2"

ingressController:
  enabled: true
  installCRDs: false
  image:
    repository: kong/kubernetes-ingress-controller
    tag: "2.1.1"
