{{- if .Values.wallarm.enabled -}}
apiVersion: v1
data:
  token: {{ .Values.wallarm.token | b64enc | quote }}
kind: Secret
metadata:
  name: {{ template "wallarm.wallarmSecret" . }}
type: Opaque
{{- end }}
